"""
Django settings for CorrectionPlatformBackend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from datetime import datetime, timedelta
from pathlib import Path

from seafileapi import SeafileAPI

DEBUG = True

ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = ['192.168.101.46','127.0.0.1']

# Application definition

CORS_ALLOWED_ORIGINS = ['http://192.168.101.57:5666',
                        "http://127.0.0.1:5666",
                        'http://192.168.101.69:3000',
                        'http://192.168.101.32']

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "accs",
        "USER": "root",
        "PASSWORD": "123456",
        "HOST": "127.0.0.1",
        "PORT": "3306",
        "CHARSET": "utf8mb4",
    },

}
