# Generated by Django 5.2 on 2025-04-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(default='avatars/default.png', max_length=255, null=True),
        ),
    ]
