# Generated by Django 5.1.7 on 2025-03-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0003_roles_remove_duser_roles_remove_duser_user_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
